### ISSUE TITLE
im creeping on github

### ISSUE THREAD

**Issue by paulinalei** [daily-bruin/travel-piece#1]

**Comment by AustinEel** [comment]
i havent even started pls

**Comment by nathanmsmith** [comment]
![jnky9cjsscmiy](https://cloud.githubusercontent.com/assets/5677971/25775828/2aa8eadc-3263-11e7-88b9-389e7ac358f4.gif)

Rare footage of @paulinalei

**Comment by paulinalei** [comment]
omg how did u find this footage dont expose me

**Comment by zeehang** [comment]
LOL
