### ISSUE TITLE
Replace day headers with Illos

### ISSUE THREAD

**Issue by zeehang** [daily-bruin/travel-piece#10]
The illos aren't running in print, so management wants to make sure that they run online.

You can find the illos below. The plan is to have them replace the Day 1, Day 2, Day 3 with the illo headers. Day 1 = Behind the Smoke, Day 2 = A Budding Industry (not yet uploaded), Day 3 = An Ounce of Hope

![an_ounce_of_hope_ final_version](https://cloud.githubusercontent.com/assets/15135987/26287844/34078396-3e38-11e7-8e02-1ff7a3dab60b.png)
![behind_the_smoke_updated_version](https://cloud.githubusercontent.com/assets/15135987/26287843/3404bc92-3e38-11e7-8997-9efd6e2e2907.png)

**Comment by AustinEel** [comment]
Exemplary work, Michael.
