### ISSUE TITLE
style the navbar nathan

### ISSUE THREAD

**Issue by AustinEel** [daily-bruin/travel-piece#3]
![navbar](https://cloud.githubusercontent.com/assets/16329673/25981708/99126062-368b-11e7-9d78-18ebc5cfdbb7.jpg)

there's a mockup you can style off of, i admit it look xbox-esque; if you think it looks shitty feel free to change it up, as long as it looks good

-have active links underlined

the current navbar is a stock bootstrap one, feel free to use any framework you want/replace it completely..(or steal the amazing one used on the Coachella 2017 page)

**Comment by AustinEel** [comment]
![db](https://cloud.githubusercontent.com/assets/16329673/25982066/2c4aec8a-368e-11e7-89b8-bfdf2cfea386.png)

heres the white db logo i used

**Comment by nwtsai** [comment]
Finished. Published to 'navbar' branch
